export type FishingSpot = {
  id: string;
  name: string;
  region: string;
  community: string;
  coordinates: { latitude: number; longitude: number };
  species: string[];
  style: string;
  approach: string;
  waterNote: string;
  mapUrl: string;
  stockingNames?: string[];
  levelUrl?: string;
};

const azgfdMap = "https://fishandboataz.azgfd.com/";

export const fishingSpots: FishingSpot[] = [
  {
    id: "upper-lake-mary",
    name: "Upper Lake Mary",
    region: "Flagstaff lakes",
    community: "Flagstaff",
    coordinates: { latitude: 34.94, longitude: -111.47 },
    species: ["Northern pike", "Walleye", "Largemouth bass", "Catfish"],
    style: "Large high-country reservoir",
    approach: "Work weed edges and points for warmwater fish. Wind can push bait to a shoreline; switch to protected coves when gusts build.",
    waterNote: "Upper Lake Mary levels vary with seasonal runoff and drought. Check current access and regulations before heading out.",
    mapUrl: azgfdMap,
  },
  {
    id: "fool-hollow",
    name: "Fool Hollow Lake",
    region: "White Mountains",
    community: "Show Low",
    coordinates: { latitude: 34.22, longitude: -110.02 },
    species: ["Rainbow trout", "Largemouth bass", "Channel catfish"],
    style: "Forest lake with shore and boat access",
    approach: "Try small lures or bait near points and accessible shoreline. Check the trout stocking schedule for the latest planting week.",
    waterNote: "AZGFD publishes a lake-level camera for Fool Hollow; verify the latest level, ramp, and campground conditions before travel.",
    mapUrl: azgfdMap,
    stockingNames: ["FOOLS HOLLOW LAKE"],
    levelUrl: "https://azgfd.jefulleralert.com/foolhollow/",
  },
  {
    id: "big-lake",
    name: "Big Lake",
    region: "White Mountains",
    community: "Apache-Sitgreaves National Forest",
    coordinates: { latitude: 33.86, longitude: -109.41 },
    species: ["Brook trout", "Cutthroat trout", "Rainbow trout"],
    style: "High-elevation trout fishery",
    approach: "Start with light line and small presentations. Cover shorelines early, then look for cooler, wind-protected water as the day warms.",
    waterNote: "A high-country destination with seasonal weather and access changes. Confirm road, campground, and lake conditions before driving in.",
    mapUrl: azgfdMap,
    levelUrl: "https://azgfd.jefulleralert.com/biglake/",
  },
  {
    id: "woods-canyon",
    name: "Woods Canyon Lake",
    region: "Mogollon Rim",
    community: "Rim Lakes Recreation Area",
    coordinates: { latitude: 34.33, longitude: -110.93 },
    species: ["Brown trout", "Rainbow trout", "Tiger trout"],
    style: "Small forest lake",
    approach: "A good lake for methodical shoreline laps. Try compact spinners, small spoons, or trout bait, and adjust depth before changing locations.",
    waterNote: "Popular with families and anglers; facilities and access are seasonal. Check the forest service status before making the trip.",
    mapUrl: azgfdMap,
  },
  {
    id: "willow-springs",
    name: "Willow Springs Lake",
    region: "Mogollon Rim",
    community: "Rim Lakes Recreation Area",
    coordinates: { latitude: 34.32, longitude: -110.99 },
    species: ["Rainbow trout", "Tiger trout"],
    style: "Large Rim lake",
    approach: "Cover open shoreline with small moving lures, then slow down with bait or flies if fish are cruising near the surface.",
    waterNote: "A popular cold-water fishery. Check current road, campground, and stocking information before heading up the Rim.",
    mapUrl: azgfdMap,
  },
  {
    id: "lees-ferry",
    name: "Lees Ferry",
    region: "Colorado River",
    community: "Glen Canyon National Recreation Area",
    coordinates: { latitude: 36.86, longitude: -111.59 },
    species: ["Rainbow trout"],
    style: "Tailwater river fishery",
    approach: "A technical trout reach. Small nymphs and streamers are common starting points; drift boat conditions and flows matter more than air temperature alone.",
    waterNote: "Special regulations apply on this rainbow trout reach. Check current Glen Canyon flows, access notices, and Arizona regulations before fishing.",
    mapUrl: azgfdMap,
    levelUrl: "https://www.usbr.gov/uc/water/crsp/cs/gcd.html",
  },
  {
    id: "lake-powell",
    name: "Lake Powell · Arizona side",
    region: "Colorado River",
    community: "Page",
    coordinates: { latitude: 36.99, longitude: -111.49 },
    species: ["Striped bass", "Smallmouth bass", "Largemouth bass", "Walleye"],
    style: "Vast desert reservoir",
    approach: "Scan for bait and surface activity before choosing a pattern. Rocky points and coves give bass anglers a useful starting structure.",
    waterNote: "The shoreline, launch access, and ramp availability shift with reservoir elevation. Check current Bureau of Reclamation and marina notices.",
    mapUrl: azgfdMap,
    levelUrl: "https://www.usbr.gov/uc/water/crsp/cs/gcd.html",
  },
  {
    id: "prescott-fain-lake",
    name: "Fain Lake",
    region: "Prescott Valley",
    community: "Prescott Valley",
    coordinates: { latitude: 34.61, longitude: -112.33 },
    species: ["Rainbow trout", "Channel catfish", "Bass", "Sunfish"],
    style: "Small community lake",
    approach: "A compact bank-fishing water. Try bait or small lures near drop-offs and shaded edges; check the stocking meter during trout season.",
    waterNote: "No boating, swimming, camping, or fires. AZGFD lists a three-acre water with park hours of 5 a.m. to 10 p.m.; verify local access before visiting.",
    mapUrl: azgfdMap,
    stockingNames: ["FAIN LAKE"],
  },
  {
    id: "prescott-yavapai-lakes",
    name: "Yavapai Lakes",
    region: "Prescott Valley",
    community: "Prescott Valley",
    coordinates: { latitude: 34.59, longitude: -112.32 },
    species: ["Rainbow trout", "Channel catfish", "Bass", "Sunfish"],
    style: "Urban community lakes",
    approach: "Keep presentations small and methodical around accessible banks. AZGFD lists trout, catfish, bass, and sunfish in the fishery limits.",
    waterNote: "A small park fishery with a walking path. Check park rules and current stocking week before your trip.",
    mapUrl: azgfdMap,
    stockingNames: ["YAVAPAI LAKES"],
  },
  {
    id: "prescott-watson-lake",
    name: "Watson Lake",
    region: "Prescott",
    community: "Prescott",
    coordinates: { latitude: 34.59, longitude: -112.45 },
    species: ["Gila trout", "Largemouth bass", "Catfish", "Sunfish"],
    style: "Granite-dotted high-desert reservoir",
    approach: "Work rocky shorelines and points with small lures. Gila trout are a native fishery; check AZGFD rules before targeting them.",
    waterNote: "AZGFD lists Gila trout as open to year-round angling here. Verify park access, water conditions, and current regulations.",
    mapUrl: azgfdMap,
    stockingNames: ["WATSON LAKE"],
  },
  {
    id: "prescott-lynx-lake",
    name: "Lynx Lake",
    region: "Prescott",
    community: "Prescott National Forest",
    coordinates: { latitude: 34.52, longitude: -112.39 },
    species: ["Rainbow trout", "Gila trout", "Largemouth bass", "Catfish"],
    style: "Forest lake",
    approach: "Try the accessible shoreline first with light tackle. Vary depth and presentation before moving between coves and points.",
    waterNote: "AZGFD lists Gila trout among fish that may be angled year-round here; verify species-specific rules and forest access.",
    mapUrl: azgfdMap,
    stockingNames: ["LYNX LAKE"],
  },
  {
    id: "prescott-goldwater-lake",
    name: "Goldwater Lake",
    region: "Prescott",
    community: "Prescott",
    coordinates: { latitude: 34.54, longitude: -112.49 },
    species: ["Rainbow trout", "Gila trout", "Catfish", "Bass"],
    style: "Ponderosa pine lake",
    approach: "Small trout lures and bait are a simple starting point. Fish shaded edges in warm weather and watch for wind across open water.",
    waterNote: "AZGFD lists Gila trout here as open to year-round angling. Check current stocking, city park notices, and regulations.",
    mapUrl: azgfdMap,
    stockingNames: ["GOLDWATER LAKE"],
  },
  {
    id: "prescott-mingus-lake",
    name: "Mingus Lake",
    region: "Prescott National Forest",
    community: "Mingus Mountain",
    coordinates: { latitude: 34.70, longitude: -112.13 },
    species: ["Rainbow trout"],
    style: "Small mountain lake",
    approach: "Use compact trout lures or bait from open shoreline. Check the latest stocking week and seasonal road status before traveling.",
    waterNote: "A small high-elevation water with seasonal access. The stocking calendar lists a planned week, not a guaranteed delivery day.",
    mapUrl: azgfdMap,
    stockingNames: ["MINGUS LAKE"],
  },
  {
    id: "flagstaff-ashurst-lake",
    name: "Ashurst Lake",
    region: "Flagstaff lakes",
    community: "Coconino National Forest",
    coordinates: { latitude: 35.03, longitude: -111.40 },
    species: ["Rainbow trout", "Northern pike"],
    style: "High-country lake",
    approach: "Cover shoreline and weed edges with small spinners or bait. Keep an eye on gusts across the open lake.",
    waterNote: "Stocking is listed by AZGFD during spring and summer. Forest roads and facilities can change seasonally.",
    mapUrl: azgfdMap,
    stockingNames: ["ASHURST LAKE"],
  },
  {
    id: "flagstaff-kinnikinick-lake",
    name: "Kinnikinick Lake",
    region: "Flagstaff lakes",
    community: "Coconino National Forest",
    coordinates: { latitude: 34.96, longitude: -111.38 },
    species: ["Rainbow trout", "Northern pike"],
    style: "Remote high-country lake",
    approach: "A quieter water for covering open banks and weed lines. Bring multiple small presentations and check wind before launching.",
    waterNote: "The AZGFD sheet lists this water as Kinnikinick Lake. Confirm road and lake access with the Forest Service.",
    mapUrl: azgfdMap,
    stockingNames: ["KINNIKINICK LAKE"],
  },
  {
    id: "flagstaff-francis-short-pond",
    name: "Francis Short Pond",
    region: "Flagstaff lakes",
    community: "Flagstaff",
    coordinates: { latitude: 35.18, longitude: -111.65 },
    species: ["Rainbow trout", "Channel catfish"],
    style: "City pond",
    approach: "A convenient walk-in option. Small bait and compact trout lures cover the basics; check the weekly schedule for the latest listed week.",
    waterNote: "Urban access and park rules apply. AZGFD includes this pond in its stocking calendar.",
    mapUrl: azgfdMap,
    stockingNames: ["FRANCIS SHORT POND"],
  },
  {
    id: "flagstaff-lower-lake-mary",
    name: "Lower Lake Mary",
    region: "Flagstaff lakes",
    community: "Flagstaff",
    coordinates: { latitude: 34.93, longitude: -111.47 },
    species: ["Rainbow trout", "Catfish"],
    style: "Shallow high-country lake",
    approach: "Water levels vary widely. Check that water is present and accessible before making the trip; fish remaining pools and channels with light tackle.",
    waterNote: "AZGFD lists Lower Lake Mary separately. Recent trout stocking is not always listed for this water.",
    mapUrl: azgfdMap,
    stockingNames: ["LOWER LAKE MARY", "L. LAKE MARY"],
  },
  {
    id: "flagstaff-mormon-lake-pond",
    name: "Mormon Lake Pond",
    region: "Flagstaff lakes",
    community: "Coconino National Forest",
    coordinates: { latitude: 34.95, longitude: -111.45 },
    species: ["Rainbow trout"],
    style: "Small forest pond",
    approach: "A small-water option when the larger lakes are windy. Check current water and access conditions before traveling.",
    waterNote: "AZGFD lists Mormon Lake Pond separately from Upper and Lower Lake Mary.",
    mapUrl: azgfdMap,
    stockingNames: ["MORMON LAKE POND"],
  },
  {
    id: "rim-bear-canyon-lake",
    name: "Bear Canyon Lake",
    region: "Mogollon Rim",
    community: "Rim Lakes Recreation Area",
    coordinates: { latitude: 34.41, longitude: -111.00 },
    species: ["Rainbow trout"],
    style: "Walk-in forest lake",
    approach: "A walk-in lake suited to light tackle and shoreline exploration. Factor the hike and changing weather into your trip plan.",
    waterNote: "Stocked during spring and summer; check Forest Service road conditions and AZGFD's latest stocking week.",
    mapUrl: azgfdMap,
    stockingNames: ["BEAR CANYON LAKE"],
  },
  {
    id: "rim-knoll-lake",
    name: "Knoll Lake",
    region: "Mogollon Rim",
    community: "Coconino National Forest",
    coordinates: { latitude: 34.46, longitude: -111.22 },
    species: ["Rainbow trout"],
    style: "Remote Rim lake",
    approach: "Use small trout presentations from accessible banks. Check road conditions and weather before heading to this remote lake.",
    waterNote: "AZGFD lists Knoll Lake in its stocking schedule; Forest Service access is seasonal.",
    mapUrl: azgfdMap,
    stockingNames: ["KNOLL LAKE"],
  },
  {
    id: "rim-blue-ridge-reservoir",
    name: "Blue Ridge Reservoir · CC Cragin",
    region: "Mogollon Rim",
    community: "Coconino National Forest",
    coordinates: { latitude: 34.31, longitude: -110.98 },
    species: ["Trout", "Smallmouth bass"],
    style: "Narrow canyon reservoir",
    approach: "Steep canyon banks favor careful access and compact presentations. Check boat-launch, road, and water-level notices before planning a launch.",
    waterNote: "AZGFD lists this as Blue Ridge Reservoir (CC Cragin) in its stocking sheet.",
    mapUrl: azgfdMap,
    stockingNames: ["BLUE RIDGE RESERVOIR CC CRAGIN"],
  },
  {
    id: "rim-christopher-creek",
    name: "Christopher Creek",
    region: "Mogollon Rim",
    community: "Christopher Creek",
    coordinates: { latitude: 34.32, longitude: -111.02 },
    species: ["Rainbow trout"],
    style: "Small mountain stream",
    approach: "Work short, shaded runs with a light presentation and approach quietly. Check stream flow and seasonal restrictions first.",
    waterNote: "AZGFD lists stocking weeks for Christopher Creek; stocking does not guarantee fish at every access point.",
    mapUrl: azgfdMap,
    stockingNames: ["CHRISTOPHER CREEK"],
  },
  {
    id: "rim-haigler-creek",
    name: "Haigler Creek",
    region: "Mogollon Rim",
    community: "Haigler Creek",
    coordinates: { latitude: 34.22, longitude: -110.97 },
    species: ["Rainbow trout"],
    style: "Small forest stream",
    approach: "Look for shaded pools and slower seams. Keep casts short and quiet in narrow water; check access before traveling.",
    waterNote: "AZGFD lists Haigler Creek in its spring/summer stocking schedule. Confirm current stream conditions and regulations.",
    mapUrl: azgfdMap,
    stockingNames: ["HAIGLER CREEK"],
  },
  {
    id: "rim-east-verde-river",
    name: "East Verde River",
    region: "Mogollon Rim",
    community: "Payson",
    coordinates: { latitude: 34.31, longitude: -111.09 },
    species: ["Rainbow trout", "Gila trout"],
    style: "Small river reaches",
    approach: "Fish accessible pools and riffle edges with a light presentation. Flows can change quickly; check the river report before entering the water.",
    waterNote: "AZGFD identifies portions of the East Verde among waters with year-round Gila trout angling. Verify boundaries and current rules.",
    mapUrl: azgfdMap,
    stockingNames: ["EAST VERDE RIVER"],
  },
  {
    id: "rim-canyon-creek",
    name: "Canyon Creek",
    region: "Mogollon Rim",
    community: "Canyon Creek",
    coordinates: { latitude: 33.80, longitude: -110.67 },
    species: ["Rainbow trout"],
    style: "Stocked mountain stream",
    approach: "Try short drifts through pools and slower runs. Stocking is marked by week, so check flows and access before driving in.",
    waterNote: "AZGFD's spring/summer schedule lists Canyon Creek among stocked waters; stream conditions vary by reach.",
    mapUrl: azgfdMap,
    stockingNames: ["CANYON CREEK"],
  },
  {
    id: "williams-dogtown-lake",
    name: "Dogtown Lake",
    region: "Williams lakes",
    community: "Kaibab National Forest",
    coordinates: { latitude: 35.26, longitude: -112.19 },
    species: ["Rainbow trout", "Channel catfish"],
    style: "Forest lake",
    approach: "Fish accessible banks with small lures or bait. Check the stocking week and forest access; conditions change with elevation and season.",
    waterNote: "AZGFD includes Dogtown Lake in the seasonal trout stocking schedule.",
    mapUrl: azgfdMap,
    stockingNames: ["DOGTOWN LAKE"],
  },
  {
    id: "williams-kaibab-lake",
    name: "Kaibab Lake",
    region: "Williams lakes",
    community: "Williams",
    coordinates: { latitude: 35.26, longitude: -112.15 },
    species: ["Rainbow trout", "Channel catfish"],
    style: "Forest lake near Williams",
    approach: "Start with small trout gear near open banks. Confirm the latest stocking week and campground or ramp status.",
    waterNote: "AZGFD lists Kaibab Lake in the seasonal trout stocking schedule.",
    mapUrl: azgfdMap,
    stockingNames: ["KAIBAB LAKE"],
  },
  {
    id: "williams-cataract-lake",
    name: "Cataract Lake",
    region: "Williams lakes",
    community: "Williams",
    coordinates: { latitude: 35.24, longitude: -112.15 },
    species: ["Rainbow trout", "Channel catfish"],
    style: "Small community lake",
    approach: "A compact shore-fishing option. Check the stocking week and local access before you go.",
    waterNote: "The AZGFD spring/summer schedule lists Cataract Lake.",
    mapUrl: azgfdMap,
    stockingNames: ["CATARACT LAKE"],
  },
  {
    id: "williams-santa-fe-lake",
    name: "Santa Fe Reservoir",
    region: "Williams lakes",
    community: "Williams",
    coordinates: { latitude: 35.17, longitude: -112.15 },
    species: ["Rainbow trout"],
    style: "Small high-country reservoir",
    approach: "Try light trout gear from accessible banks and check AZGFD's latest listed stocking week.",
    waterNote: "The schedule lists Santa Fe Lake; verify local access and water conditions before traveling.",
    mapUrl: azgfdMap,
    stockingNames: ["SANTA FE LAKE"],
  },
  {
    id: "white-mountains-show-low-lake",
    name: "Show Low Lake",
    region: "White Mountains",
    community: "Show Low",
    coordinates: { latitude: 34.26, longitude: -110.05 },
    species: ["Rainbow trout", "Largemouth bass", "Channel catfish"],
    style: "Town reservoir",
    approach: "Check the seasonal trout stocking week, then cover points and accessible shorelines with small lures or bait.",
    waterNote: "A popular Show Low-area lake. Confirm current ramp, park, and regulation details before your trip.",
    mapUrl: azgfdMap,
    stockingNames: ["SHOW LOW LAKE"],
  },
  {
    id: "white-mountains-rainbow-lake",
    name: "Rainbow Lake",
    region: "White Mountains",
    community: "Pinetop-Lakeside",
    coordinates: { latitude: 34.16, longitude: -109.99 },
    species: ["Rainbow trout", "Largemouth bass", "Channel catfish"],
    style: "Neighborhood lake",
    approach: "Fish accessible banks and weed edges with compact lures or bait. Check AZGFD for the latest listed trout week.",
    waterNote: "The stocking list uses the name Rainbow Lake; verify public access and local rules before fishing.",
    mapUrl: azgfdMap,
    stockingNames: ["RAINBOW LAKE"],
  },
  {
    id: "white-mountains-silver-creek",
    name: "Silver Creek",
    region: "White Mountains",
    community: "Show Low area",
    coordinates: { latitude: 34.63, longitude: -109.89 },
    species: ["Trout"],
    style: "Cold-water creek",
    approach: "Use a light presentation and check stream flow before choosing a reach. Special rules may apply on managed sections.",
    waterNote: "AZGFD marks Silver Creek in its stocking schedule. Check the current regulation booklet for section-specific rules.",
    mapUrl: azgfdMap,
    stockingNames: ["SILVER CREEK"],
  },
  {
    id: "white-mountains-becker-lake",
    name: "Becker Lake",
    region: "Springerville lakes",
    community: "Springerville",
    coordinates: { latitude: 34.97, longitude: -109.57 },
    species: ["Rainbow trout", "Brown trout"],
    style: "Managed trout lake",
    approach: "Use light tackle and work the shoreline before changing depth. Check stocking notes and special regulations before fishing.",
    waterNote: "A managed fishery with rules that can differ from statewide defaults. Confirm current AZGFD regulations.",
    mapUrl: azgfdMap,
    stockingNames: ["BECKER LAKE"],
  },
  {
    id: "white-mountains-luna-lake",
    name: "Luna Lake",
    region: "White Mountains",
    community: "Luna Lake",
    coordinates: { latitude: 34.46, longitude: -109.38 },
    species: ["Rainbow trout", "Brown trout"],
    style: "High-country lake",
    approach: "Try small trout lures and bait around accessible banks. Check the stocking meter and local access before heading out.",
    waterNote: "The AZGFD schedule lists Luna Lake among stocked waters; seasonal weather can affect road and shoreline access.",
    mapUrl: azgfdMap,
    stockingNames: ["LUNA LAKE"],
  },
  {
    id: "white-mountains-lee-valley-lake",
    name: "Lee Valley Lake",
    region: "White Mountains",
    community: "Apache-Sitgreaves National Forest",
    coordinates: { latitude: 34.07, longitude: -109.39 },
    species: ["Trout"],
    style: "Remote high-country lake",
    approach: "Use small trout presentations and prepare for cold, changeable weather. Check forest-road status and regulations before travel.",
    waterNote: "A remote White Mountains water; the current stocking schedule may not list a recent week.",
    mapUrl: azgfdMap,
    stockingNames: ["LEE VALLEY LAKE"],
  },
  {
    id: "verde-valley-oak-creek",
    name: "Oak Creek",
    region: "Verde Valley",
    community: "Sedona area",
    coordinates: { latitude: 34.87, longitude: -111.76 },
    species: ["Rainbow trout", "Brown trout"],
    style: "Red-rock stream",
    approach: "Approach clear pools quietly with small flies or lures. Check flow, closures, and special regulations for the exact reach.",
    waterNote: "AZGFD lists Oak Creek in its spring/summer schedule. Conditions and rules vary along the creek.",
    mapUrl: azgfdMap,
    stockingNames: ["OAK CREEK"],
  },
  {
    id: "verde-valley-beaver-creek",
    name: "Beaver Creek",
    region: "Verde Valley",
    community: "Camp Verde area",
    coordinates: { latitude: 34.56, longitude: -111.85 },
    species: ["Rainbow trout"],
    style: "Creek and stocked reach",
    approach: "Look for shaded pools and slower seams with light tackle. Check flow and the specific access point before fishing.",
    waterNote: "The stocking schedule labels the managed reach Beaver Creek (Wet); verify current access and regulations.",
    mapUrl: azgfdMap,
    stockingNames: ["BEAVER CREEK WET"],
  },
  {
    id: "verde-valley-west-clear-creek",
    name: "West Clear Creek",
    region: "Verde Valley",
    community: "Camp Verde area",
    coordinates: { latitude: 34.47, longitude: -111.72 },
    species: ["Rainbow trout"],
    style: "Canyon creek",
    approach: "Plan for a hike to many access points. Small lures or flies suit narrow water; check flow, weather, and access advisories first.",
    waterNote: "The schedule lists West Clear Creek, but a marked week is not a guarantee for every reach.",
    mapUrl: azgfdMap,
    stockingNames: ["WEST CLEAR CREEK"],
  },
];

export const defaultFishingSpot = fishingSpots[0];
